name = "PrincipalMomentAnalysisApp"
uuid = "e56c3062-542c-497d-ab50-e8a2f2a25ce2"
authors = ["Rasmus Henningsson", "Lund University"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
